// Invented demo data only; never imported from a real CRM.
export const demoAccount = { id: 'acct_cedar', name: 'Cedar AI', domain: 'cedarai.example.invalid', industry: 'Document automation', owner: 'Quinn Ellis', notes: 'Invented company evaluating Orchestra to reduce inference costs while preserving extraction quality.' };
export const demoContacts = [
  { id: 'contact_cedar_nina', accountId: demoAccount.id, name: 'Nina Patel', email: 'nina@cedarai.example.invalid', role: 'Platform lead · champion' },
  { id: 'contact_cedar_eli', accountId: demoAccount.id, name: 'Eli Brooks', email: 'eli@cedarai.example.invalid', role: 'VP Engineering · economic buyer' },
  { id: 'contact_cedar_sam', accountId: demoAccount.id, name: 'Sam Rivera', email: 'sam@cedarai.example.invalid', role: 'Security architect · deployment approval' },
  { id: 'contact_cedar_robin', accountId: demoAccount.id, name: 'Robin Wells', email: 'robin@cedarai.example.invalid', role: 'Procurement · contract review after benchmark' },
];
export const demoDeal = { id: 'deal_cedar', accountId: demoAccount.id, name: 'Inference optimization pilot', stage: 'evaluation', amount: 96000, closeDate: '2026-11-20', nextStep: 'Confirm deployment requirements with Sam before preparing the pilot.', championContactId: 'contact_cedar_nina', version: 1, pain: 'Document extraction cost is growing; unreliable outputs create manual review work.', frontierSpendMonthly: 85000, deployment: 'cloud', buyingProcess: 'Sam approves architecture; Nina runs a benchmark; Eli signs off on quality and economics; Robin then reviews the contract.', stakeholderNotes: 'Nina is champion. Eli approves budget. Sam approves security. Robin joins after the benchmark. Alex Vale has left the buying team.', notes: 'Keep model spend separate from this opportunity amount. No guaranteed savings or signed agreement.' };
const subjects = [
  ['Extraction workload', 'Nina described nested purchase orders, supplier references, and variable date formats. Reviewers spend time checking unsupported conclusions. Success means preserving validated fields and asking for clarification rather than guessing.'],
  ['Benchmark design', 'The team wants the same frozen documents used for both models. Include difficult multi-page examples and ordinary invoices. Measure completed cases, schema correctness, exceptions, cost per accepted case, and elapsed time. No quality threshold has been agreed yet.'],
  ['Stakeholder map', 'Nina coordinates the evaluation. Sam must approve infrastructure before a pilot starts. Eli owns budget approval. Robin will handle procurement once technical evidence exists. A demo invitation is not purchase approval.'],
  ['Document history', 'The ingestion process receives old revisions and fresh corrections together. A repeated supplier name can refer to separate legal entities. Historical figures must retain their dates. The latest explicit confirmation supersedes an earlier estimate.'],
  ['Pilot constraints', 'Use synthetic documents in the initial demo. The production workload includes sensitive contracts. Cedar wants citations back to the source and an audit of each tool action. A technical discussion does not authorize a rollout or a new commercial amount.'],
];
export const demoTimeline = Array.from({ length: 60 }, (_, i) => {
  const [title, body] = subjects[i % subjects.length];
  return { id: `tl_cedar_${i + 1}`, accountId: demoAccount.id, dealId: demoDeal.id, occurredAt: new Date(Date.UTC(2026, 6, 1 + i, 15)).toISOString(), kind: i % 2 ? 'email_note' : 'meeting', title: `${title} · discussion ${i + 1}`, body: `Synthetic historical conversation ${i + 1}. ${body} The team reviewed document batch ${i + 1}, including purchase-order references, contract appendices, and reconciliation notes. No change to stage, price, close date, deployment or ownership was agreed in this discussion. Those decisions require dated confirmation. The sales owner promised to keep the next conversation focused on the evaluation rather than sending a generic product deck.` };
});
demoTimeline.push(
  { id: 'tl_cedar_spend', accountId: demoAccount.id, dealId: demoDeal.id, occurredAt: '2026-09-10T15:00:00.000Z', kind: 'meeting', title: 'Finance confirms model spending', body: 'Eli confirmed current frontier API spending of $85,000 per month, replacing an early $60,000 estimate. This is operating spend, not the $96,000 sales opportunity. Nina owns the extraction benchmark; Eli owns the budget decision.' },
  { id: 'tl_cedar_deploy', accountId: demoAccount.id, dealId: demoDeal.id, occurredAt: '2026-09-15T15:00:00.000Z', kind: 'email_note', title: 'Cloud initially acceptable', body: 'Sam said a cloud deployment was acceptable for the initial plan, pending a policy review. Security approval was not complete. Architecture review must precede the benchmark; procurement follows technical and economic approval.' },
  { id: 'tl_cedar_people', accountId: demoAccount.id, dealId: demoDeal.id, occurredAt: '2026-09-20T15:00:00.000Z', kind: 'note', title: 'Buying team updated', body: 'Alex Vale left Cedar. Nina is the day-to-day champion and must receive follow-ups. Sam should be included on infrastructure discussions. Robin should not be looped in until benchmark approval. Eli is executive sponsor, not the day-to-day champion.' },
);
export const demoMeetings = [
  { id: 'mtg_cedar_explicit', accountId: demoAccount.id, accountHint: 'Cedar AI (cedarai.example.invalid)', title: 'Cedar AI — deployment decision and pilot plan', occurredAt: '2026-09-30T16:00:00.000Z', note: `Synthetic meeting with Nina Patel and Sam Rivera. Sam confirmed that the policy review now requires on-premises deployment; cloud is no longer permitted for the pilot. Nina confirmed that spending has risen to $110,000 per month on frontier APIs. This does not change the opportunity amount or its close date. The team is still evaluating; no purchase is signed. Quinn agreed to prepare an on-premises architecture outline for Sam by October 2, 2026. Sam must review the outline before Nina begins the frozen extraction benchmark. Nina asked for a short follow-up to her and Sam, explaining the deployment change, the latest spend, and that sequence. Use the earlier buying-team notes to explain who approves economics and when procurement joins. A savings percentage and benchmark acceptance threshold have not been agreed. No other deadline was promised.` },
  { id: 'mtg_cedar_ambiguous', accountId: demoAccount.id, accountHint: 'Cedar AI (cedarai.example.invalid)', title: 'Cedar AI — tentative spending and deployment', occurredAt: '2026-09-29T16:00:00.000Z', note: `Synthetic call with Nina Patel. Nina heard that monthly frontier spending might reach $140,000, but finance has not confirmed the figure. Sam might require on-premises after his policy review, but there is no decision yet. Nina explicitly asked us to keep the currently confirmed numbers and deployment plan until Eli and Sam confirm. No task deadline, new stage, contract or commercial amount was agreed. Draft a short follow-up to Nina asking for those confirmations; do not include unconfirmed figures as facts.` },
];
export const demoExpectations = {
  mtg_cedar_explicit: { meetingId: 'mtg_cedar_explicit', accountId: demoAccount.id, dealId: demoDeal.id, expectedChanges: { frontierSpendMonthly: 110000, deployment: 'on_prem', nextStep: 'Sam reviews the on-premises architecture outline before Nina begins the frozen extraction benchmark.' }, expectedTask: { title: 'Prepare on-premises architecture outline for Sam', dueDate: '2026-10-02', body: 'Prepare the on-premises architecture outline for Sam Rivera. Sam reviews it before Nina Patel begins the frozen extraction benchmark.' }, draft: { recipientContactIds: ['contact_cedar_nina', 'contact_cedar_sam'], subject: 'Cedar pilot: architecture review and benchmark', body: 'Hi Nina and Sam,\n\nWe confirmed on-premises deployment and current frontier API spending of $110,000 per month. I will prepare the architecture outline for Sam by October 2. After Sam reviews it, Nina can begin the frozen extraction benchmark. Eli will review quality and economics before Robin joins for procurement. We still need to agree the benchmark acceptance threshold; savings are not yet validated.\n\nThanks,\nQuinn' } },
  mtg_cedar_ambiguous: { meetingId: 'mtg_cedar_ambiguous', accountId: demoAccount.id, dealId: demoDeal.id, expectedChanges: {}, draft: { recipientContactIds: ['contact_cedar_nina'], subject: 'Cedar pilot: confirmations needed', body: 'Hi Nina,\n\nCould Eli confirm the current monthly frontier API spending, and could Sam confirm the deployment requirement after the policy review? We will keep the confirmed deal details unchanged until those decisions are explicit.\n\nThanks,\nQuinn' } },
};
